# Generated by Django 4.2 on 2023-04-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foobar", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
